[package]
name = "scope"
version = "0.3.1"
authors = ["David Pederson <dpederson@figure.com>"]
edition = "2018"

exclude = [
  "scope.wasm",
  "checksums.txt",
]

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
backtraces = []

[dependencies]
provwasm-std = { path = "../../packages/bindings", version = "0.13.0" }
cosmwasm-std = { version = "0.13.0" }
cosmwasm-storage = { version = "0.13.0" }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.20" }


[dev-dependencies]
provwasm-mocks = { path = "../../packages/mocks", version = "0.13.0" }
cosmwasm-schema = { version = "0.13.0" }
