[package]
name = "scope"
version = "1.0.0-beta"
authors = ["David Pederson <dpederson@figure.com>", "Ken Talley <ktalley@figure.com>"]
edition = "2018"

exclude = [
  "scope.wasm",
  "checksums.txt",
]

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
backtraces = []

[dependencies]
provwasm-std = { path = "../../packages/bindings" }
cosmwasm-std = { version = "1.0.0-beta5", default-features = false }
cosmwasm-storage = { version = "1.0.0-beta5" }
schemars = "0.8.1"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.20" }


[dev-dependencies]
provwasm-mocks = { path = "../../packages/mocks" }
cosmwasm-schema = { version = "1.0.0-beta5" }
