name: Tests / Code Coverage
#  Tests / Code Coverage workflow runs unit tests and uploads a code coverage report
#  This workflow is run on pushes to master & every Pull Request,
#  if no *.go, go.mod or go.sum file is changed it will pass without running as these are required checks
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  #  This action cleans up previously running instances of a workflow on the same branch. This accomplishes
  #  the task of automatically cancelling CI runs on pushes to the same branch, which is a common feature in
  #  most CI systems but currently not possible with GitHub actions.
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"

  build_init:
    runs-on: ubuntu-latest
    name: Build Init
    steps:
      - id: version
        run: echo "::set-output name=version::${GITHUB_REF##*/}"
    outputs:
      version: ${{ steps.version.outputs.version }}
      go_version: "1.17"

  build_smart_contracts:
    runs-on: ubuntu-latest
    needs:
      - build_init
    name: Build Smart Contracts
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: ${{ needs.build_init.outputs.go_version }}
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libleveldb-dev
      - name: Add wasm32 target
        run: |
          rustup target add wasm32-unknown-unknown
      - name: Build wasm binary
        run: |
          cd ./contracts
          make all

  test_smart_contracts:
    runs-on: ubuntu-latest
    needs:
      - build_init
    name: Test Smart Contracts
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2.1.5
      with:
        go-version: ${{ needs.build_init.outputs.go_version }}
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libleveldb-dev
      - name: Add wasm32 target
        run: |
          rustup target add wasm32-unknown-unknown
      - name: Test contracts
        run: |
          make test