name: Tests / Code Coverage
#  Tests / Code Coverage workflow runs unit tests and uploads a code coverage report
#  This workflow is run on pushes to master & every Pull Request,
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  #  This action cleans up previously running instances of a workflow on the same branch. This accomplishes
  #  the task of automatically cancelling CI runs on pushes to the same branch, which is a common feature in
  #  most CI systems but currently not possible with GitHub actions.
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"

  build_init:
    runs-on: ubuntu-latest
    name: Build Init
    steps:
      - id: version
        run: echo "::set-output name=version::${GITHUB_REF##*/}"
    outputs:
      version: ${{ steps.version.outputs.version }}
      go_version: "1.17"

  build_smart_contracts:
    runs-on: ubuntu-latest
    needs:
      - build_init
    name: Build Smart Contracts
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: ${{ needs.build_init.outputs.go_version }}
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libleveldb-dev
      - name: Add wasm32 target
        run: |
          rustup target add wasm32-unknown-unknown
      - name: Build wasm binary
        run: |
          cd ./contracts
          make all

  test_tutorial_smart_contract:
    runs-on: ubuntu-latest
    needs:
      - build_init
    name: Test Tutorial Smart Contract
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: ${{ needs.build_init.outputs.go_version }}
      - name: Smart Contract Test setup
        uses: ./ # Uses an action in the root directory
        id: tutorial
        with:
          provenance_version: "v1.8.0"
          test_script: "./scripts/tutorial_test.sh"

#  test_tutorial_smart_contract:
#    runs-on: ubuntu-latest
#    needs:
#      - build_init
#    name: Test Tutorial Smart Contract
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Setup go
#        uses: actions/setup-go@v2.1.5
#        with:
#          go-version: ${{ needs.build_init.outputs.go_version }}
#      - name: Install deps
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y libleveldb-dev
#      - name: Add wasm32 target
#        run: |
#          rustup target add wasm32-unknown-unknown
#      - name: Test contract
#        run: |
#          make test-tutorial

  test_attrs_smart_contract:
    runs-on: ubuntu-latest
    needs:
      - build_init
    name: Test Attr Smart Contract
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: ${{ needs.build_init.outputs.go_version }}
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libleveldb-dev
      - name: Add wasm32 target
        run: |
          rustup target add wasm32-unknown-unknown
      - name: Test contract
        run: |
          make test-attrs

  test_marker_smart_contract:
    runs-on: ubuntu-latest
    needs:
      - build_init
    name: Test Marker Smart Contract
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: ${{ needs.build_init.outputs.go_version }}
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libleveldb-dev
      - name: Add wasm32 target
        run: |
          rustup target add wasm32-unknown-unknown
      - name: Test contract
        run: |
          make test-marker

  test_name_smart_contract:
    runs-on: ubuntu-latest
    needs:
      - build_init
    name: Test Name Smart Contract
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: ${{ needs.build_init.outputs.go_version }}
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libleveldb-dev
      - name: Add wasm32 target
        run: |
          rustup target add wasm32-unknown-unknown
      - name: Test contract
        run: |
          make test-name

  test_scope_smart_contract:
    runs-on: ubuntu-latest
    needs:
      - build_init
    name: Test Scope Smart Contract
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: ${{ needs.build_init.outputs.go_version }}
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libleveldb-dev
      - name: Add wasm32 target
        run: |
          rustup target add wasm32-unknown-unknown
      - name: Test contract
        run: |
          make test-scope